# GitHub Actions workflow for Mood Tracker App (Node.js/Express + React)
# This workflow installs dependencies, runs backend and frontend tests, builds the frontend, and checks linting.
# It is designed for reliability and best practices.

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend (Node.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    env:
      NODE_ENV: test
      JWT_SECRET: testsecret
      # Add other required env vars here
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint backend
        run: |
          if [ -f .eslintrc.js ] || [ -f .eslintrc.json ]; then npm run lint || true; fi

      - name: Run backend tests
        run: |
          if [ -f package.json ] && grep -q 'test' package.json; then npm test; else echo "No backend tests found."; fi

  frontend:
    name: Frontend (React)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client/mood-tracker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint frontend
        run: |
          if [ -f .eslintrc.js ] || [ -f .eslintrc.json ]; then npm run lint || true; fi

      - name: Run frontend tests
        run: |
          if [ -f package.json ] && grep -q 'test' package.json; then npm test -- --watchAll=false; else echo "No frontend tests found."; fi

      - name: Build frontend
        run: |
          npm run build
          if [ ! -f build/index.html ]; then echo "React build failed: index.html not found"; exit 1; fi

      - name: Copy frontend build to backend public
        run: |
          rm -rf ../../server/public
          cp -r build ../../server/public
          if [ ! -f ../../server/public/index.html ]; then echo "Copy failed: index.html not found in server/public"; exit 1; fi

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    environment:
      name: 'production'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verify frontend build exists in server/public
        run: |
          if [ ! -f server/public/index.html ]; then echo "ERROR: index.html not found in server/public. Deployment will fail."; exit 1; fi

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy backend (with frontend) to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: server

      # If deploying frontend as part of the same Web App, copy build to server/public or similar as needed.
      # Or, if using Azure Static Web Apps, uncomment and configure the following:
      # - name: Deploy frontend to Azure Static Web Apps
      #   uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     action: 'upload'
      #     app_location: 'client/mood-tracker/build'
      #     output_location: ''
